
CREATE OR REPLACE MATERIALIZED VIEW my_uc_catalog.dlt_test.GOLD_DAILY_SALES_SUMMARY
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.enableChangeDataFeed' = 'true'
)
AS
SELECT
  o.O_ORDERDATE AS SALE_DATE,
  o.ORDER_YEAR,
  o.ORDER_QUARTER,
  o.ORDER_MONTH,
  o.ORDER_DAY_OF_WEEK,
  o.O_ORDERSTATUS,
  o.ORDER_STATUS_DESC,
  COUNT(DISTINCT o.O_ORDERKEY) AS TOTAL_ORDERS,
  COUNT(DISTINCT o.O_CUSTKEY) AS UNIQUE_CUSTOMERS,
  SUM(l.FINAL_PRICE) AS TOTAL_REVENUE,
  SUM(l.DISCOUNTED_PRICE) AS TOTAL_DISCOUNTED_REVENUE,
  SUM(l.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNTS_GIVEN,
  SUM(l.TAX_AMOUNT) AS TOTAL_TAX_COLLECTED,
  AVG(l.FINAL_PRICE) AS AVG_LINE_ITEM_REVENUE,
  SUM(l.L_QUANTITY) AS TOTAL_QUANTITY_SOLD,
  COUNT(l.L_LINENUMBER) AS TOTAL_LINE_ITEMS,
  ROUND(AVG(l.DISCOUNT_PERCENT), 2) AS AVG_DISCOUNT_PERCENT,
  COUNT(CASE WHEN o.ORDER_SIZE_CATEGORY = 'ENTERPRISE' THEN 1 END) AS ENTERPRISE_ORDERS,
  COUNT(CASE WHEN o.ORDER_SIZE_CATEGORY = 'LARGE' THEN 1 END) AS LARGE_ORDERS,
  COUNT(CASE WHEN o.ORDER_SIZE_CATEGORY = 'MEDIUM' THEN 1 END) AS MEDIUM_ORDERS,
  COUNT(CASE WHEN o.ORDER_SIZE_CATEGORY = 'SMALL' THEN 1 END) AS SMALL_ORDERS,
  COUNT(CASE WHEN o.PRIORITY_RANK = 1 THEN 1 END) AS URGENT_ORDERS,
  ROUND(AVG(l.SHIPPING_DAYS), 1) AS AVG_SHIPPING_DAYS,
  COUNT(CASE WHEN l.DELIVERY_PERFORMANCE = 'ON_TIME' THEN 1 END) AS ON_TIME_DELIVERIES,
  ROUND(COUNT(CASE WHEN l.DELIVERY_PERFORMANCE = 'ON_TIME' THEN 1 END) * 100.0 / NULLIF(COUNT(l.L_LINENUMBER), 0), 2) AS ON_TIME_DELIVERY_RATE
FROM my_uc_catalog.dlt_test.SILVER_ORDERS o
LEFT JOIN my_uc_catalog.dlt_test.SILVER_LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY 
GROUP BY 
  o.O_ORDERDATE, o.ORDER_YEAR, o.ORDER_QUARTER, o.ORDER_MONTH, 
  o.ORDER_DAY_OF_WEEK, o.O_ORDERSTATUS, o.ORDER_STATUS_DESC;