


CREATE OR REPLACE MATERIALIZED VIEW my_uc_catalog.dlt_test.GOLD_CUSTOMER_ORDERS_SUMMARY
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.enableChangeDataFeed' = 'true'
)
AS
SELECT
  c.C_CUSTKEY,
  c.C_NAME,
  c.C_MKTSEGMENT,
  c.ACCOUNT_BALANCE_TIER,
  c.C_NATIONKEY,
  COUNT(DISTINCT o.O_ORDERKEY) AS TOTAL_ORDERS,
  COUNT(DISTINCT CASE WHEN o.ORDER_STATUS_DESC = 'FULFILLED' THEN o.O_ORDERKEY END) AS FULFILLED_ORDERS,
  COUNT(DISTINCT CASE WHEN o.ORDER_STATUS_DESC = 'OPEN' THEN o.O_ORDERKEY END) AS OPEN_ORDERS,
  SUM(o.O_TOTALPRICE) AS TOTAL_REVENUE,
  AVG(o.O_TOTALPRICE) AS AVG_ORDER_VALUE,
  MIN(o.O_TOTALPRICE) AS MIN_ORDER_VALUE,
  MAX(o.O_TOTALPRICE) AS MAX_ORDER_VALUE,
  MIN(o.O_ORDERDATE) AS FIRST_ORDER_DATE,
  MAX(o.O_ORDERDATE) AS LAST_ORDER_DATE,
  DATEDIFF(DAY, MIN(o.O_ORDERDATE), MAX(o.O_ORDERDATE)) AS CUSTOMER_LIFETIME_DAYS,
  COUNT(DISTINCT o.ORDER_YEAR) AS ACTIVE_YEARS,
  COUNT(DISTINCT CASE WHEN o.PRIORITY_RANK <= 2 THEN o.O_ORDERKEY END) AS HIGH_PRIORITY_ORDERS,
  ROUND(AVG(o.PRIORITY_RANK), 2) AS AVG_PRIORITY_RANK,
  MAX(o.ORDER_SIZE_CATEGORY) AS LARGEST_ORDER_CATEGORY,
  CASE 
    WHEN COUNT(DISTINCT o.O_ORDERKEY) >= 10 THEN 'VIP'
    WHEN COUNT(DISTINCT o.O_ORDERKEY) >= 5 THEN 'FREQUENT'
    WHEN COUNT(DISTINCT o.O_ORDERKEY) >= 2 THEN 'REGULAR'
    ELSE 'OCCASIONAL'
  END AS CUSTOMER_SEGMENT
FROM my_uc_catalog.dlt_test.SILVER_CUSTOMER c
LEFT JOIN my_uc_catalog.dlt_test.SILVER_ORDERS o ON c.C_CUSTKEY = o.O_CUSTKEY
GROUP BY c.C_CUSTKEY, c.C_NAME, c.C_MKTSEGMENT, c.ACCOUNT_BALANCE_TIER, c.C_NATIONKEY
;
