

CREATE OR REPLACE MATERIALIZED VIEW my_uc_catalog.dlt_test.GOLD_ORDER_LINEITEM_SUMMARY
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.enableChangeDataFeed' = 'true'
)
AS
SELECT
  o.O_ORDERKEY,
  o.O_CUSTKEY,
  o.O_ORDERSTATUS,
  o.ORDER_STATUS_DESC,
  o.O_ORDERDATE,
  o.ORDER_YEAR,
  o.ORDER_QUARTER,
  o.ORDER_MONTH,
  o.ORDER_SIZE_CATEGORY,
  o.PRIORITY_RANK,
  COUNT(l.L_LINENUMBER) AS TOTAL_LINE_ITEMS,
  SUM(l.L_QUANTITY) AS TOTAL_QUANTITY,
  SUM(l.L_EXTENDEDPRICE) AS TOTAL_EXTENDED_PRICE,
  SUM(l.DISCOUNTED_PRICE) AS TOTAL_DISCOUNTED_PRICE,
  SUM(l.FINAL_PRICE) AS TOTAL_FINAL_PRICE,
  SUM(l.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT_AMOUNT,
  SUM(l.TAX_AMOUNT) AS TOTAL_TAX_AMOUNT,
  ROUND(AVG(l.DISCOUNT_PERCENT), 2) AS AVG_DISCOUNT_PERCENT,
  ROUND(AVG(l.TAX_PERCENT), 2) AS AVG_TAX_PERCENT,
  ROUND(AVG(l.SHIPPING_DAYS), 1) AS AVG_SHIPPING_DAYS,
  COUNT(CASE WHEN l.DELIVERY_PERFORMANCE = 'ON_TIME' THEN 1 END) AS ON_TIME_DELIVERIES,
  COUNT(CASE WHEN l.DELIVERY_PERFORMANCE = 'LATE' THEN 1 END) AS LATE_DELIVERIES,
  ROUND(COUNT(CASE WHEN l.DELIVERY_PERFORMANCE = 'ON_TIME' THEN 1 END) * 100.0 / NULLIF(COUNT(l.L_LINENUMBER), 0), 2) AS ON_TIME_DELIVERY_RATE,
  COUNT(CASE WHEN l.DISCOUNT_TIER = 'HIGH_DISCOUNT' THEN 1 END) AS HIGH_DISCOUNT_ITEMS,
  COUNT(CASE WHEN l.L_RETURNFLAG = 'R' THEN 1 END) AS RETURNED_ITEMS,
  MAX(l.L_SHIPMODE) AS PRIMARY_SHIP_MODE
FROM my_uc_catalog.dlt_test.SILVER_ORDERS o
LEFT JOIN my_uc_catalog.dlt_test.SILVER_LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY 
GROUP BY 
  o.O_ORDERKEY, o.O_CUSTKEY, o.O_ORDERSTATUS, o.ORDER_STATUS_DESC,
  o.O_ORDERDATE, o.ORDER_YEAR, o.ORDER_QUARTER, o.ORDER_MONTH,
  o.ORDER_SIZE_CATEGORY, o.PRIORITY_RANK;

