

CREATE OR REPLACE MATERIALIZED VIEW my_uc_catalog.dlt_test.SILVER_ORDERS
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.enableChangeDataFeed' = 'true'
)
AS
SELECT
  O_ORDERKEY,
  O_CUSTKEY,
  UPPER(TRIM(O_ORDERSTATUS)) AS O_ORDERSTATUS,
  CASE UPPER(TRIM(O_ORDERSTATUS))
    WHEN 'O' THEN 'OPEN'
    WHEN 'F' THEN 'FULFILLED'
    WHEN 'P' THEN 'PENDING'
    ELSE 'UNKNOWN'
  END AS ORDER_STATUS_DESC,
  O_TOTALPRICE,
  CASE 
    WHEN O_TOTALPRICE < 1000 THEN 'SMALL'
    WHEN O_TOTALPRICE BETWEEN 1000 AND 10000 THEN 'MEDIUM'
    WHEN O_TOTALPRICE BETWEEN 10000 AND 50000 THEN 'LARGE'
    ELSE 'ENTERPRISE'
  END AS ORDER_SIZE_CATEGORY,
  O_ORDERDATE,
  YEAR(O_ORDERDATE) AS ORDER_YEAR,
  QUARTER(O_ORDERDATE) AS ORDER_QUARTER,
  MONTH(O_ORDERDATE) AS ORDER_MONTH,
  DAYOFWEEK(O_ORDERDATE) AS ORDER_DAY_OF_WEEK,
  UPPER(TRIM(O_ORDERPRIORITY)) AS O_ORDERPRIORITY,
  CASE UPPER(TRIM(O_ORDERPRIORITY))
    WHEN '1-URGENT' THEN 1
    WHEN '2-HIGH' THEN 2
    WHEN '3-MEDIUM' THEN 3
    WHEN '4-NOT SPECIFIED' THEN 4
    WHEN '5-LOW' THEN 5
    ELSE 99
  END AS PRIORITY_RANK,
  UPPER(TRIM(O_CLERK)) AS O_CLERK,
  O_SHIPPRIORITY,
  TRIM(O_COMMENT) AS O_COMMENT
FROM my_uc_catalog.dlt_test.BRONZE_ORDERS;


