

CREATE OR REPLACE MATERIALIZED VIEW my_uc_catalog.dlt_test.SILVER_LINEITEM
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.enableChangeDataFeed' = 'true'
)
AS
SELECT
  L_ORDERKEY,
  L_PARTKEY,
  L_SUPPKEY,
  L_LINENUMBER,
  L_QUANTITY,
  L_EXTENDEDPRICE,
  L_DISCOUNT,
  L_TAX,
  UPPER(TRIM(L_RETURNFLAG)) AS L_RETURNFLAG,
  UPPER(TRIM(L_LINESTATUS)) AS L_LINESTATUS,
  CASE UPPER(TRIM(L_LINESTATUS))
    WHEN 'O' THEN 'OPEN'
    WHEN 'F' THEN 'FULFILLED'
    ELSE 'UNKNOWN'
  END AS LINE_STATUS_DESC,
  L_SHIPDATE,
  L_COMMITDATE,
  L_RECEIPTDATE,
  UPPER(TRIM(L_SHIPINSTRUCT)) AS L_SHIPINSTRUCT,
  UPPER(TRIM(L_SHIPMODE)) AS L_SHIPMODE,
  TRIM(L_COMMENT) AS L_COMMENT,
  L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS DISCOUNTED_PRICE,
  L_EXTENDEDPRICE * (1 - L_DISCOUNT) * (1 + L_TAX) AS FINAL_PRICE,
  L_EXTENDEDPRICE * L_DISCOUNT AS DISCOUNT_AMOUNT,
  L_EXTENDEDPRICE * (1 - L_DISCOUNT) * L_TAX AS TAX_AMOUNT,
  ROUND((L_DISCOUNT * 100), 2) AS DISCOUNT_PERCENT,
  ROUND((L_TAX * 100), 2) AS TAX_PERCENT,
  CASE 
    WHEN L_DISCOUNT = 0 THEN 'NO_DISCOUNT'
    WHEN L_DISCOUNT <= 0.05 THEN 'LOW_DISCOUNT'
    WHEN L_DISCOUNT <= 0.10 THEN 'MEDIUM_DISCOUNT'
    ELSE 'HIGH_DISCOUNT'
  END AS DISCOUNT_TIER,
  DATEDIFF(DAY, L_SHIPDATE, L_RECEIPTDATE) AS SHIPPING_DAYS,
  DATEDIFF(DAY, L_COMMITDATE, L_RECEIPTDATE) AS DAYS_FROM_COMMIT,
  CASE 
    WHEN L_RECEIPTDATE <= L_COMMITDATE THEN 'ON_TIME'
    WHEN DATEDIFF(DAY, L_COMMITDATE, L_RECEIPTDATE) <= 3 THEN 'SLIGHTLY_LATE'
    ELSE 'LATE'
  END AS DELIVERY_PERFORMANCE
FROM my_uc_catalog.dlt_test.BRONZE_LINEITEM;

